/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import repository.AkunRepositoryImpl;

/**
 *
 * @author auliazhar
 */
public class AdminMenu extends javax.swing.JFrame {
    private String name;
    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }
    
    public AdminMenu(String name){
        this.name = name;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        logoutBTN = new javax.swing.JButton();
        incBarangBTN = new javax.swing.JButton();
        incStokBTN = new javax.swing.JButton();
        decStokBTN = new javax.swing.JButton();
        viewBarangBTN = new javax.swing.JButton();
        sayHi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Admin");
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBTN.setBackground(java.awt.Color.white);
        logoutBTN.setFont(new java.awt.Font("JetBrains Mono NL", 1, 12)); // NOI18N
        logoutBTN.setForeground(java.awt.Color.black);
        logoutBTN.setText("Logout");
        logoutBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBTNMouseExited(evt);
            }
        });
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });
        jPanel4.add(logoutBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 150, 30));

        incBarangBTN.setBackground(new java.awt.Color(255, 255, 255));
        incBarangBTN.setFont(new java.awt.Font("JetBrains Mono NL", 1, 10)); // NOI18N
        incBarangBTN.setForeground(new java.awt.Color(0, 0, 0));
        incBarangBTN.setText("Kurang Stok Barang");
        incBarangBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        incBarangBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incBarangBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                incBarangBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                incBarangBTNMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                incBarangBTNMousePressed(evt);
            }
        });
        jPanel4.add(incBarangBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 30));

        incStokBTN.setBackground(new java.awt.Color(255, 255, 255));
        incStokBTN.setFont(new java.awt.Font("JetBrains Mono NL", 1, 10)); // NOI18N
        incStokBTN.setForeground(new java.awt.Color(0, 0, 0));
        incStokBTN.setText("Tambah Barang Baru");
        incStokBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        incStokBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incStokBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                incStokBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                incStokBTNMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                incStokBTNMousePressed(evt);
            }
        });
        jPanel4.add(incStokBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 30));

        decStokBTN.setBackground(new java.awt.Color(255, 255, 255));
        decStokBTN.setFont(new java.awt.Font("JetBrains Mono NL", 1, 10)); // NOI18N
        decStokBTN.setForeground(new java.awt.Color(0, 0, 0));
        decStokBTN.setText("Lihat Barang");
        decStokBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        decStokBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decStokBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decStokBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                decStokBTNMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                decStokBTNMousePressed(evt);
            }
        });
        jPanel4.add(decStokBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, 30));

        viewBarangBTN.setBackground(new java.awt.Color(255, 255, 255));
        viewBarangBTN.setFont(new java.awt.Font("JetBrains Mono NL", 1, 10)); // NOI18N
        viewBarangBTN.setForeground(new java.awt.Color(0, 0, 0));
        viewBarangBTN.setText("Tambah Stok Barang");
        viewBarangBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewBarangBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBarangBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewBarangBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewBarangBTNMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewBarangBTNMousePressed(evt);
            }
        });
        jPanel4.add(viewBarangBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 30));

        sayHi.setFont(new java.awt.Font("Serif", 1, 65)); // NOI18N
        sayHi.setForeground(java.awt.Color.black);
        sayHi.setText("Hi, " + name);
        jPanel4.add(sayHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 45, 500, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background/Menu BG.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBTNMouseEntered
        // TODO add your handling code here:
        logoutBTN.setForeground(new java.awt.Color(25, 143, 216));
    }//GEN-LAST:event_logoutBTNMouseEntered

    private void logoutBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBTNMouseExited
        // TODO add your handling code here:
        logoutBTN.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_logoutBTNMouseExited

    private void incBarangBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incBarangBTNMouseEntered
        // TODO add your handling code here:
        incBarangBTN.setForeground(new java.awt.Color(25, 143, 216));
    }//GEN-LAST:event_incBarangBTNMouseEntered

    private void incBarangBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incBarangBTNMouseExited
        // TODO add your handling code here:
        incBarangBTN.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_incBarangBTNMouseExited

    private void incBarangBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incBarangBTNMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_incBarangBTNMouseClicked

    private void incBarangBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incBarangBTNMousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_incBarangBTNMousePressed

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void incStokBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incStokBTNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_incStokBTNMouseClicked

    private void incStokBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incStokBTNMouseEntered
        // TODO add your handling code here:
        incStokBTN.setForeground(new java.awt.Color(25, 143, 216));
    }//GEN-LAST:event_incStokBTNMouseEntered

    private void incStokBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incStokBTNMouseExited
        // TODO add your handling code here:
        incStokBTN.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_incStokBTNMouseExited

    private void incStokBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incStokBTNMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_incStokBTNMousePressed

    private void decStokBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decStokBTNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_decStokBTNMouseClicked

    private void decStokBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decStokBTNMouseEntered
        // TODO add your handling code here:
        decStokBTN.setForeground(new java.awt.Color(25, 143, 216));
    }//GEN-LAST:event_decStokBTNMouseEntered

    private void decStokBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decStokBTNMouseExited
        // TODO add your handling code here:
        decStokBTN.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_decStokBTNMouseExited

    private void decStokBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decStokBTNMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_decStokBTNMousePressed

    private void viewBarangBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBarangBTNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBarangBTNMouseClicked

    private void viewBarangBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBarangBTNMouseEntered
        // TODO add your handling code here:
        viewBarangBTN.setForeground(new java.awt.Color(25, 143, 216));
    }//GEN-LAST:event_viewBarangBTNMouseEntered

    private void viewBarangBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBarangBTNMouseExited
        // TODO add your handling code here:
        viewBarangBTN.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_viewBarangBTNMouseExited

    private void viewBarangBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBarangBTNMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBarangBTNMousePressed
    
//      
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decStokBTN;
    private javax.swing.JButton incBarangBTN;
    private javax.swing.JButton incStokBTN;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JLabel sayHi;
    private javax.swing.JButton viewBarangBTN;
    // End of variables declaration//GEN-END:variables
}
